#钱包里的一个地址的私钥,unisat钱包导出私钥可以看到（最后一栏 Hex Private Key）,
#注意：配置好私钥后，先运行命令 “ go run . ”，程序会将对应地址导入到本地节点，之后再将btc充值到这个地址上，之所以这样是因为会检测不到导入前地址上的余额
PrivateKey: "" 


Mint:
  RuneId: "1:0"  #Mint符文，修改RuneId
  MintNum: 100   #mint几张
 

FeePerByte: 2  #gas费率 设置为0的时候会自动使用链上gas，可能会偏高
LocalRpcUrl: "http://节点用户名:节点密码@127.0.0.1:端口号"  #本地的rpc节点，端口默认是8332


#启动加速的话当UTXO到达<Unconfirmeds>的时候，则会获取 <SpeedFee> 进行无限次加速（当前utxo上需要保证足够余额）
IsAutoSpeed: 1 #1：启动加速； 0不启动
SpeedFee: 4 #当需要加速的时候，设置卡着的每笔交易想加速到多少gas，如果设置为0，则会自动从链上获取当前区块gas
Unconfirmeds: 25 #当卡着的交易大于等于设置的值时候开始加速



#不需要动，获取当前区块gas时候会用到，这种方式相对准确
Network: "mainnet" # mainnet 
RpcUrl: "https://mempool.fractalbitcoin.io/api" #https://mempool.space/api 
UtxoAmount: 330
